In [8]:
import numpy as np
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b
print(c)
print(c.shape)

[[-0.10749182 -1.90370783 -1.48089214]
 [-1.18101405 -2.1021844  -2.22357711]]
(2, 3)


In [10]:
import numpy as np
x = np.random.randn(4, 3) # a.shape = (2, 3)
y = np.random.randn(3, 2) # b.shape = (2, 1)
z = x * y
print(z)
print(z.shape)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [25]:
import numpy as np
a = np.random.randn(12288,150) # a.shape = (2, 3)
b = np.random.randn(150,45) # b.shape = (2, 1)
c = np.dot(a,b)
print(c)
print(c.shape)

[[ -8.72842458  -4.5520809    1.88698265 ...,  11.23204532 -21.54824026
   -3.07311556]
 [-21.28884312  -4.22778443 -17.53298545 ...,  -7.64839477  -8.10052415
    0.3003105 ]
 [  2.67311267  -6.66634268   5.54003522 ...,   6.58606438  -0.27974077
   21.25788411]
 ..., 
 [ -8.57102144   6.54624216 -11.11550054 ...,   5.2811888    2.80524363
   12.60962771]
 [-12.71509594  21.71467544 -12.25538836 ..., -11.97580268  16.76497035
    7.14911579]
 [ 20.77318835 -10.65295926   4.95331179 ...,   9.03379553   3.54663335
   -2.84433046]]
(12288, 45)


In [13]:
a = np.random.randn(3, 3)
print("a = ",a )
b = np.random.randn(3, 1)
print("b = ",b )
c = a*b
print(c)
print(c.shape)

a =  [[-1.05670192  0.58005734  0.81376758]
 [ 1.50130698  0.30430814  0.60787257]
 [-2.02920083  0.52355347 -0.69046294]]
b =  [[ 1.1450312 ]
 [-0.11738066]
 [-0.00467403]]
[[-1.20995667  0.66418375  0.93178927]
 [-0.1762244  -0.03571989 -0.07135248]
 [ 0.00948454 -0.0024471   0.00322724]]
(3, 3)


In [17]:
a = np.random.randn(3, 3)
print("a = ",a )
b = np.random.randn(3, 1)
print("b = ",b )
c = a*b
print("c=",c)
print(c.shape)

a =  [[-1.05534475  1.45672778 -0.11882258]
 [-1.8977785   0.14256917  0.51356218]
 [ 0.14739455  1.19432719  0.29314145]]
b =  [[ 0.78232923]
 [-0.37648784]
 [-0.80879556]]
b =  (3, 1)
c= [[-0.82562705  1.13964072 -0.09295838]
 [ 0.71449052 -0.05367556 -0.19334992]
 [-0.11921206 -0.96596653 -0.2370915 ]]
(3, 3)


In [19]:
# a.shape = (3,4)
# b.shape = (4,1)

a = np.random.randn(3, 4)
b = np.random.randn(4, 1)

for i in range(3):
    for j in range(4):
        c[i][j] = a[i][j] + b[j]
print("c=",c)
print(c.shape)

c= [[-0.37372816 -1.28809315  0.9945395 ]
 [ 0.28947813  0.17465571 -0.82242289]
 [ 1.49093546  0.58480024 -0.55658542]]
(3, 3)


In [24]:
import numpy as np
b = np.random.randn(4, 1)
print("b=",b)
print("b[1]=",b[1])

b= [[-0.38050509]
 [ 0.30432654]
 [ 0.53731449]
 [-0.03675312]]
b[1]= [ 0.30432654]
